#!/usr/bin/env php
<?php

echo "pulling from git\n";
passthru("sudo git pull");

echo "running liquibase\n";
passthru('php dbchanges/liquibase/update.php');

echo "executing node update";
passthru('npm update');

echo "composer update";
passthru('php tools/composer self-update');
passthru('php tools/composer update --working-dir=application/');

echo 'updating assets';
passthru('./node_modules/.bin/gulp production');

echo 'updating file permissions' ;
passthru('sudo cp assets_src/css/fonts.less assets/local/css/fonts.css');
passthru('chmod 777 -R uploads/');
passthru('chmod 777 -R assets/cache');
passthru('chmod 777 application/config/email.php');
passthru('chmod 777 assets/vendor/css/custom.css');
passthru('chmod 777 assets/vendor/css/material-dashboard.base.css');

if (file_exists('./application/modules/traductions')) {
	echo 'updating traductions' ;
	define('BASEPATH', 'toto');
	$db = array();
	putenv('LANG=fr_FR.UTF-8');
	putenv('APPLICATION_ENV=default');

	require_once __DIR__ . '/../application/config/database.php';

	$liquibaseJarFile = __DIR__ . '/../application/modules/traductions/third_party/translate.jar';

	$db_active = $db[$active_group];

	$username = $db_active['username'];
	$password = $db_active['password'];
	$dbhost = $db_active['hostname'];
	$dbname = $db_active['database'];
	$output = array();
	echo "generating traductions\n";
	foreach (array('fr', 'en', 'ru') as $lang) {
		passthru("java -jar $liquibaseJarFile translate . $lang $dbhost,$dbname,$username,$password 2>&1", $output);
	}
}



